openapi: 3.0.3
info:
  title: Видеоплатформа API
  description: API для сервиса видеоплатформы с регистрацией, аутентификацией, загрузкой и управлением видео, оценками и видеоплеером.
  version: 1.0.0

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegistration:
      type: object
      required:
        - email
        - password
        - username
      properties:
        email:
          type: string
          format: email
          example: user@itmo.ru
        password:
          type: string
          format: password
          minLength: 6
          example: strongPassword123
        username:
          type: string
          minLength: 3
          example: Username

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: strongPassword123

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: UserUsername
        role:
          type: string
          example: user
        avatarUrl:
          type: string
          format: uri
          example: https://cdn.videoplatform.com/avatars/user123.png

    UpdateUserProfile:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          example: NewUsername
        password:
          type: string
          format: password
          minLength: 6

    UpdateUserAvatarRequest:
      type: object
      properties:
        avatar:
          type: string
          format: binary

    VideoUpload:
      type: object
      required:
        - title
        - description
        - file
      properties:
        title:
          type: string
          example: Заголовок видео
        description:
          type: string
          example: Описание видео
        file:
          type: string
          format: binary

    Video:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        title:
          type: string
          example: Заголовок видео
        description:
          type: string
          example: Описание видео
        url:
          type: string
          format: uri
          example: https://cdn.videoplatform.com/videos/video123.mp4
        thumbnailUrl:
          type: string
          format: uri
          example: https://cdn.videoplatform.com/thumbnails/video123.png
        uploadedBy:
          $ref: '#/components/schemas/UserProfile'
        uploadDate:
          type: string
          format: date-time
          example: "2024-04-27T10:00:00Z"
        views:
          type: integer
          example: 1024
        likes:
          type: integer
          example: 100
        dislikes:
          type: integer
          example: 5

    VideoSearchResponse:
      type: object
      properties:
        total:
          type: integer
          example: 50
        videos:
          type: array
          items:
            $ref: '#/components/schemas/Video'

    UpdateVideoRequest:
      type: object
      properties:
        title:
          type: string
          example: Обновленный заголовок
        description:
          type: string
          example: Обновленное описание

    Comment:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174002"
        videoId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        author:
          $ref: '#/components/schemas/UserProfile'
        content:
          type: string
          example: Отличное видео!
        createdAt:
          type: string
          format: date-time
          example: "2024-04-27T10:05:00Z"

    CreateCommentRequest:
      type: object
      required:
        - videoId
        - content
      properties:
        videoId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        content:
          type: string
          minLength: 1
          example: Отличное видео!

    CommentSearchResponse:
      type: object
      properties:
        total:
          type: integer
          example: 100
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'

    GetReactionsResponse:
      type: object
      properties:
        likes:
          type: integer
          example: 100
        dislikes:
          type: integer
          example: 5

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Something went wrong

  parameters:
    VideoId:
      name: videoId
      in: path
      required: true
      description: Идентификатор видео
      schema:
        type: string
        format: uuid

    CommentId:
      name: commentId
      in: path
      required: true
      description: Идентификатор комментария
      schema:
        type: string
        format: uuid

security:
  - BearerAuth: []

paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      tags:
        - Аутентификация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Аутентификация пользователя
      tags:
        - Аутентификация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        '401':
          description: Неверные учетные данные

  #
  # Профиль пользователя
  #

  /users/{userId}:
    get:
      summary: Получение профиля пользователя
      tags:
        - Пользователи
      parameters:
        - name: userId
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
            format: uuid
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Профиль пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: Пользователь не найден

    put:
      summary: Обновление профиля пользователя
      tags:
        - Пользователи
      parameters:
        - name: userId
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
            format: uuid
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfile'
      responses:
        '200':
          description: Профиль обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав
        '404':
          description: Пользователь не найден

  /users/{userId}/avatar:
    put:
      summary: Обновление фото профиля пользователя
      tags:
        - Пользователи
      parameters:
        - name: userId
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
            format: uuid
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateUserAvatarRequest'
      responses:
        '200':
          description: Профиль обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав
        '404':
          description: Пользователь не найден

  #
  # Видео
  #

  /videos:
    post:
      summary: Загрузка видео
      tags:
        - Видео
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VideoUpload'
      responses:
        '201':
          description: Видео успешно загружено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав


    get:
      summary: Поиск видео
      tags:
        - Видео
      parameters:
        - name: query
          in: query
          required: true
          description: Строка поиска по названию и описанию
          schema:
            type: string
            example: "учебное видео"
        - name: page
          in: query
          required: false
          description: Номер страницы
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          description: Количество результатов на странице
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Результаты поиска
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoSearchResponse'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /videos/{videoId}:
    get:
      summary: Получение информации о видео
      tags:
        - Видео
      parameters:
        - $ref: '#/components/parameters/VideoId'
      responses:
        '200':
          description: Информация о видео
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '404':
          description: Видео не найдено

    put:
      summary: Редактирование информации о видео
      tags:
        - Видео
      parameters:
        - $ref: '#/components/parameters/VideoId'
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVideoRequest'
      responses:
        '200':
          description: Видео обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав
        '404':
          description: Видео не найдено

    delete:
      summary: Удаление видео
      tags:
        - Видео
      parameters:
        - $ref: '#/components/parameters/VideoId'
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Видео удалено
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав
        '404':
          description: Видео не найдено

  #
  # Комментарии к видео
  #

  /comments:
    get:
      summary: Получение комментариев к видео
      tags:
        - Комментарии
      parameters:
        - name: videoId
          in: query
          required: true
          description: Идентификатор видео
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          required: false
          description: Номер страницы
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          description: Количество комментариев на странице
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentSearchResponse'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Видео не найдено

    post:
      summary: Добавление комментария к видео
      tags:
        - Комментарии
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentRequest'
      responses:
        '201':
          description: Комментарий добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '404':
          description: Видео не найдено

  /comments/{commentId}:
    delete:
      summary: Удаление комментария
      tags:
        - Комментарии
      parameters:
        - $ref: '#/components/parameters/CommentId'
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Комментарий удален
        '401':
          description: Не авторизован
        '403':
          description: Недостаточно прав
        '404':
          description: Комментарий не найден

  #
  # Реакции на видео
  #

  /videos/{videoId}/reactions:
    get:
      summary: Получить реакции для видео
      tags:
        - Реакции
      parameters:
        - $ref: '#/components/parameters/VideoId'
      responses:
        '200':
          description: Список реакций
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReactionsResponse'
        '404':
          description: Видео не найдено

  /videos/{videoId}/like:
    post:
      summary: Поставить лайк на видео
      tags:
        - Реакции
      parameters:
        - $ref: '#/components/parameters/VideoId'
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Реакция поставлена
        '401':
          description: Не авторизован
        '404':
          description: Видео не найдено

  /videos/{videoId}/dislike:
    post:
      summary: Поставить дизлайк на видео
      tags:
        - Реакции
      parameters:
        - $ref: '#/components/parameters/VideoId'
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Реакция поставлена
        '401':
          description: Не авторизован
        '404':
          description: Видео не найдено

tags:
  - name: Аутентификация
    description: Регистрация и аутентификация пользователей
  - name: Пользователи
    description: Управление профилями пользователей
  - name: Видео
    description: Загрузка, управление и поиск видео
  - name: Комментарии
    description: Управление комментариями под видео
  - name: Реакции
    description: Реакции на видео